name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
          java-package: jre # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x86 # (x64 or x86) - defaults to x64
    
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
